version: 0.2

env:
  variables:
    AWS_CLOUDFORMATION_TEMPLATE: cloudformation/base-cloudformation.yml

phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.8
    commands:
      - pip3 install --upgrade awscli
  pre_build:
    commands:
      aws cloudformation validate-template --template-body file://${AWS_CLOUDFORMATION_TEMPLATE}

artifacts:
  files:
    - cloudformation/base-cloudformation.yml
